name: dart_stats
description: A stats library translated from the npm javascript packages chi-squared-test, chi-squared, and gamma
# version: 1.0.0
# author: Tim Whiting <tim@whitings.org>

environment:
  sdk: ">=2.7.0 <3.0.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
