name: dart_statistics
description: A stats library translated from the npm javascript packages chi-squared-test, chi-squared, and gamma
version: 0.1.0-nullsafety.0
homepage: https://github.com/TimWhiting/dart_statistics.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  test: ^1.16.0-nullsafety.11
